tid = "2636739"
title = "N2过了好耶～"
url = "//north-plus.net/"
forum = ""
total_floors = 0
created_at = 2025-08-25T17:36:09.354482+08:00

[main_post]
  floor = "GF"
  content = "上回考了八十多惦记了半年，这下能睡个好觉了 n1暂时就不考虑了，先学英语好应付考试 现在就感觉自己超强超棒的 等晚上吃顿好的去"
  html_content = "上回考了八十多惦记了半年，这下能睡个好觉了<img src=\"images/post/smile/kaomoji/29.gif\" loading=\"lazy\"/>\n                                            <br/>\n                                            n1暂时就不考虑了，先学英语好应付考试<img src=\"images/post/smile/smallface/face106.gif\" loading=\"lazy\"/>\n                                            <br/>\n                                            现在就感觉自己超强超棒的<img src=\"images/post/smile/smallface/face095.gif\" loading=\"lazy\"/>\n                                            <br/>\n                                            等晚上吃顿好的去<img src=\"images/post/smile/smallface/face113.jpg\" loading=\"lazy\"/>\n                                            <br/>\n                                            <span id=\"att_433233\">\n                                                <b></b>\n                                                <br/>\n                                                <img src=\"//north-plus.net/attachment/Mon_2508/9_1178845_eaeb05a2f12cc3d.png\" loading=\"lazy\" border=\"0\" onclick=\"if(this.width&gt;=680) window.open(&#39;//north-plus.net/attachment/Mon_2508/9_1178845_eaeb05a2f12cc3d.png&#39;);\" onload=\"if(this.width&gt;&#39;680&#39;)this.width=&#39;680&#39;;\"/>\n                                            </span>"
  post_time = 2025-08-25T17:36:09.354482+08:00
  post_id = "tpc"
  [main_post.author]
    username = "路过之人"
    uid = ""
    avatar = "images/post/smile/smallface/face106.gif"
    post_count = 0
    register_date = ""
    last_login = ""
    signature = ""

  [[main_post.images]]
    url = "//north-plus.net/attachment/Mon_2508/9_1178845_eaeb05a2f12cc3d.png"
    local_path = ""
    alt = ""
    is_attachment = true
    file_size = 0
    downloaded = false

[[replies]]
  floor = "B1F"
  content = "恭喜"
  html_content = "\n                                            恭喜 <img src=\"images/post/smile/smallface/face077.gif\" loading=\"lazy\"/>\n                                        "
  post_time = 2025-08-25T17:36:09.354683+08:00
  post_id = "34668163"
  [replies.author]
    username = "364c6e34"
    uid = ""
    avatar = "images/face/none.gif"
    post_count = 0
    register_date = ""
    last_login = ""
    signature = ""

[[replies]]
  floor = "B2F"
  content = "80分都不够，多少分才算及格"
  html_content = "80分都不够，多少分才算及格"
  post_time = 2025-08-25T17:36:09.354763+08:00
  post_id = "34668166"
  [replies.author]
    username = "稻妻母猪神里绫华"
    uid = ""
    avatar = "images/face/8.gif"
    post_count = 0
    register_date = ""
    last_login = ""
    signature = ""

[[replies]]
  floor = "B3F"
  content = "90，因为满分180"
  html_content = "\n                                            90，因为满分180 <img src=\"images/post/smile/smallface/face106.gif\" loading=\"lazy\"/>\n                                        "
  post_time = 2025-08-25T17:36:09.354848+08:00
  post_id = "34668171"
  [replies.author]
    username = "路过之人"
    uid = ""
    avatar = "images/post/smile/smallface/face106.gif"
    post_count = 0
    register_date = ""
    last_login = ""
    signature = ""

[[replies]]
  floor = "B4F"
  content = "我n1也擦线过了102"
  html_content = "\n                                            <img src=\"images/post/smile/smallface/face113.jpg\" loading=\"lazy\"/>我n1也擦线过了102\n                                        "
  post_time = 2025-08-25T17:36:09.354927+08:00
  post_id = "34668194"
  [replies.author]
    username = "勇敢牛牛不怕牛牛"
    uid = ""
    avatar = "images/face/none.gif"
    post_count = 0
    register_date = ""
    last_login = ""
    signature = ""
