tid = "2636739"
title = "N2过了好耶～"
url = "//north-plus.net/"
forum = "茶馆"
total_floors = 5
created_at = 2025-08-25T11:14:00Z

[main_post]
  floor = "GF"
  content = "上回考了八十多惦记了半年，这下能睡个好觉了 n1暂时就不考虑了，先学英语好应付考试 现在就感觉自己超强超棒的 等晚上吃顿好的去"
  html_content = "上回考了八十多惦记了半年，这下能睡个好觉了<img src=\"images/post/smile/kaomoji/29.gif\" loading=\"lazy\"/>\n                                            <br/>\n                                            n1暂时就不考虑了，先学英语好应付考试<img src=\"images/post/smile/smallface/face106.gif\" loading=\"lazy\"/>\n                                            <br/>\n                                            现在就感觉自己超强超棒的<img src=\"images/post/smile/smallface/face095.gif\" loading=\"lazy\"/>\n                                            <br/>\n                                            等晚上吃顿好的去<img src=\"images/post/smile/smallface/face113.jpg\" loading=\"lazy\"/>\n                                            <br/>\n                                            <span id=\"att_433233\">\n                                                <b></b>\n                                                <br/>\n                                                <img src=\"//north-plus.net/attachment/Mon_2508/9_1178845_eaeb05a2f12cc3d.png\" loading=\"lazy\" border=\"0\" onclick=\"if(this.width>=680) window.open('//north-plus.net/attachment/Mon_2508/9_1178845_eaeb05a2f12cc3d.png');\" onload=\"if(this.width>'680')this.width='680';\"/>\n                                            </span>"
  post_time = 2025-08-25T11:14:00Z
  post_id = "tpc"
  [main_post.author]
    username = "路过之人"
    uid = "1178845"
    avatar = "https://p.sda1.dev/12/ed933e250b3bb83b434a76db3cfdc175/108897981_p0.jpg"
    post_count = 5178
    register_date = "2019-07-26"
    last_login = "2025-08-25"
    signature = "有什么有意思的事情吗？"

  [[main_post.images]]
    url = "//north-plus.net/attachment/Mon_2508/9_1178845_eaeb05a2f12cc3d.png"
    local_path = ""
    alt = ""
    is_attachment = true
    file_size = 0
    downloaded = false

[[replies]]
  floor = "B1F"
  content = "恭喜"
  html_content = "\n                                            恭喜 <img src=\"images/post/smile/smallface/face077.gif\" loading=\"lazy\"/>\n                                        "
  post_time = 2025-08-25T11:17:00Z
  post_id = "34668163"
  [replies.author]
    username = "364c6e34"
    uid = "1982404"
    avatar = "images/face/none.gif"
    post_count = 29
    register_date = "2024-01-24"
    last_login = "2025-08-25"
    signature = ""

[[replies]]
  floor = "B2F"
  content = "80分都不够，多少分才算及格"
  html_content = "80分都不够，多少分才算及格"
  post_time = 2025-08-25T11:18:00Z
  post_id = "34668166"
  [replies.author]
    username = "稻妻母猪神里绫华"
    uid = "925904"
    avatar = "images/face/8.gif"
    post_count = 1654
    register_date = "2018-03-17"
    last_login = "2025-08-25"
    signature = ""

[[replies]]
  floor = "B3F"
  content = "90，因为满分180"
  html_content = "\n                                            90，因为满分180 <img src=\"images/post/smile/smallface/face106.gif\" loading=\"lazy\"/>\n                                        "
  post_time = 2025-08-25T11:19:00Z
  post_id = "34668171"
  [replies.author]
    username = "路过之人"
    uid = "1178845"
    avatar = "https://p.sda1.dev/12/ed933e250b3bb83b434a76db3cfdc175/108897981_p0.jpg"
    post_count = 5178
    register_date = "2019-07-26"
    last_login = "2025-08-25"
    signature = "有什么有意思的事情吗？"

[[replies]]
  floor = "B4F"
  content = "我n1也擦线过了102"
  html_content = "\n                                            <img src=\"images/post/smile/smallface/face113.jpg\" loading=\"lazy\"/>我n1也擦线过了102\n                                        "
  post_time = 2025-08-25T11:26:00Z
  post_id = "34668194"
  [replies.author]
    username = "勇敢牛牛不怕牛牛"
    uid = "1310667"
    avatar = "images/face/none.gif"
    post_count = 333
    register_date = "2020-05-06"
    last_login = "2025-08-25"
    signature = "勇敢牛牛不怕困难"